specVersion: 1
id: web-design-guidelines
title: Web Interface Guidelines
description: Review UI code for Web Interface Guidelines compliance. Use when
  asked to "review my UI", "check accessibility", "audit design", "review UX",
  or "check my site against best practices".
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:28:02.101Z
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/vercel-labs/agent-skills
  path: skills/web-design-guidelines
  ref: main
  commit: c4399b192588e71fdf0cb507c7b6ad9e9657ce6b
