specVersion: 1
id: react-best-practices
title: Vercel React Best Practices
description: React and Next.js performance optimization guidelines from Vercel
  Engineering. This skill should be used when writing, reviewing, or refactoring
  React/Next.js code to ensure optimal performance patterns. Triggers on tasks
  involving React components, Next.js pages, data fetching, bundle optimization,
  or performance improvements.
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:28:02.101Z
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/vercel-labs/agent-skills
  path: skills/react-best-practices
  ref: main
  commit: c4399b192588e71fdf0cb507c7b6ad9e9657ce6b
