specVersion: 1
id: ask-questions-if-underspecified
title: Ask Questions If Underspecified
description: Clarify requirements before implementing. Use when serious doubts araise.
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:28:02.101Z
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/trailofbits/skills
  path: plugins/ask-questions-if-underspecified/skills/ask-questions-if-underspecified
  ref: main
  commit: 2a7b3d9cd56dab7bf622f65996bc5071fac8e015
