specVersion: 1
id: algorithmic-art
title: algorithmic-art
description: Creating algorithmic art using p5.js with seeded randomness and
  interactive parameter exploration. Use this when users request creating art
  using code, generative art, algorithmic art, flow fields, or particle systems.
  Create original algorithmic art rather than copying existing artists' work to
  avoid copyright violations.
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/algorithmic-art
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
