specVersion: 1
id: xlsx
title: Requirements for Outputs
description: "Comprehensive spreadsheet creation, editing, and analysis with
  support for formulas, formatting, data analysis, and visualization. When
  Claude needs to work with spreadsheets (.xlsx, .xlsm, .csv, .tsv, etc) for:
  (1) Creating new spreadsheets with formulas and formatting, (2) Reading or
  analyzing data, (3) Modify existing spreadsheets while preserving formulas,
  (4) Data analysis and visualization in spreadsheets, or (5) Recalculating
  formulas"
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/xlsx
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
