specVersion: 1
id: brand-guidelines
title: Anthropic Brand Styling
description: Applies Anthropic's official brand colors and typography to any
  sort of artifact that may benefit from having Anthropic's look-and-feel. Use
  it when brand colors or style guidelines, visual formatting, or company design
  standards apply.
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:39:41.583Z
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/brand-guidelines
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
