specVersion: 1
id: doc-coauthoring
title: Doc Co-Authoring Workflow
description: Guide users through a structured workflow for co-authoring
  documentation. Use when user wants to write documentation, proposals,
  technical specs, decision docs, or similar structured content. This workflow
  helps users efficiently transfer context, refine content through iteration,
  and verify the doc works for readers. Trigger when user mentions writing docs,
  creating proposals, drafting specs, or similar documentation tasks.
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:39:41.583Z
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/doc-coauthoring
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
