export type RegistryIndex = {
  specVersion: number;
  generatedAt: string;
  skills: RegistrySkill[];
};

export type RegistryCategories = {
  specVersion: number;
  generatedAt: string;
  categories: RegistryCategory[];
};

export type RegistryCategory = {
  id: string;
  title: string;
  description?: string;
  subcategories: RegistrySubcategory[];
};

export type RegistrySubcategory = {
  id: string;
  title: string;
  description?: string;
};

export type RepositoryInfo = {
  url: string;
  owner: string;
  name: string;
  avatar?: string;
  stars?: number;
  forks?: number;
  updatedAt?: string;
};

export type RegistrySkill = {
  specVersion: number;
  id: string;
  title: string;
  description: string;
  createdAt?: string;
  updatedAt?: string;
  license?: string;
  authors?: Array<{ name: string; url?: string; email?: string }>;
  tags?: string[];
  agents?: string[];
  runtime?: string[];
  links?: { homepage?: string; docs?: string; repo?: string };
  source?: { repo?: string; path?: string; ref?: string; commit?: string };
  related?: string[];

  // Repository metadata (from .x_skill.yaml - internal system data)
  repository?: RepositoryInfo;

  // Derived fields (generated by build-registry).
  category: string;
  subcategory: string;
  repoPath: string;
  summary?: string;
  files?: Array<{ path: string; kind: "file" }>;
};
