specVersion: 1
id: web-artifacts-builder
title: Web Artifacts Builder
description: Suite of tools for creating elaborate, multi-component claude.ai
  HTML artifacts using modern frontend web technologies (React, Tailwind CSS,
  shadcn/ui). Use for complex artifacts requiring state management, routing, or
  shadcn/ui components - not for simple single-file HTML/JSX artifacts.
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/web-artifacts-builder
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
