specVersion: 1
id: mcp-builder
title: MCP Server Development Guide
description: Guide for creating high-quality MCP (Model Context Protocol)
  servers that enable LLMs to interact with external services through
  well-designed tools. Use when building MCP servers to integrate external APIs
  or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/mcp-builder
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
