specVersion: 1
id: frontend-design
title: frontend-design
description: Create distinctive, production-grade frontend interfaces with high
  design quality. Use this skill when the user asks to build web components,
  pages, artifacts, posters, or applications (examples include websites, landing
  pages, dashboards, React components, HTML/CSS layouts, or when
  styling/beautifying any web UI). Generates creative, polished code and UI
  design that avoids generic AI aesthetics.
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/frontend-design
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
