specVersion: 1
id: ui-ux-pro-max
title: UI/UX Pro Max - Design Intelligence
description: "UI/UX design intelligence. 50 styles, 21 palettes, 50 font
  pairings, 20 charts, 9 stacks (React, Next.js, Vue, Svelte, SwiftUI, React
  Native, Flutter, Tailwind, shadcn/ui). Actions: plan, build, create, design,
  implement, review, fix, improve, optimize, enhance, refactor, check UI/UX
  code. Projects: website, landing page, dashboard, admin panel, e-commerce,
  SaaS, portfolio, blog, mobile app, .html, .tsx, .vue, .svelte. Elements:
  button, modal, navbar, sidebar, card, table, form, chart. Styles:
  glassmorphism, claymorphism, minimalism, brutalism, neumorphism, bento grid,
  dark mode, responsive, skeuomorphism, flat design. Topics: color palette,
  accessibility, animation, layout, typography, font pairing, spacing, hover,
  shadow, gradient. Integrations: shadcn/ui MCP for component search and
  examples."
tags:
  - ui
  - ux
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/nextlevelbuilder/ui-ux-pro-max-skill
  path: .claude/skills/ui-ux-pro-max
  ref: main
  commit: 3eb7d99d67b6e7a33807463dbbb0d01940a96e1f
