specVersion: 1
id: webapp-testing
title: Web Application Testing
description: Toolkit for interacting with and testing local web applications
  using Playwright. Supports verifying frontend functionality, debugging UI
  behavior, capturing browser screenshots, and viewing browser logs.
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/webapp-testing
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
