specVersion: 1
id: vercel-deploy-claimable
title: Vercel Deploy
description: Deploy applications and websites to Vercel. Use this skill when the
  user requests deployment actions such as "Deploy my app", "Deploy this to
  production", "Create a preview deployment", "Deploy and give me the link", or
  "Push this live". No authentication required - returns preview URL and
  claimable deployment link.
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:28:02.101Z
tags:
  - test123
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/vercel-labs/agent-skills
  path: skills/claude.ai/vercel-deploy-claimable
  ref: main
  commit: c4399b192588e71fdf0cb507c7b6ad9e9657ce6b
