specVersion: 1
id: canvas-design
title: canvas-design
description: Create beautiful visual art in .png and .pdf documents using design
  philosophy. You should use this skill when the user asks to create a poster,
  piece of art, design, or other static piece. Create original visual designs,
  never copying existing artists' work to avoid copyright violations.
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:39:41.583Z
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/canvas-design
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
