specVersion: 1
id: skill-creator
title: Skill Creator
description: Guide for creating effective skills. This skill should be used when
  users want to create a new skill (or update an existing skill) that extends
  Claude's capabilities with specialized knowledge, workflows, or tool
  integrations.
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/skill-creator
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
