specVersion: 1
id: internal-comms
title: internal-comms
description: A set of resources to help me write all kinds of internal
  communications, using the formats that my company likes to use. Claude should
  use this skill whenever asked to write some sort of internal communications
  (status reports, leadership updates, 3P updates, company newsletters, FAQs,
  incident reports, project updates, etc.).
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/internal-comms
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
