specVersion: 1
id: slack-gif-creator
title: Slack GIF Creator
description: Knowledge and utilities for creating animated GIFs optimized for
  Slack. Provides constraints, validation tools, and animation concepts. Use
  when users request animated GIFs for Slack like "make me a GIF of X doing Y
  for Slack.
createdAt: 2026-01-27T02:28:02.101Z
updatedAt: 2026-01-27T02:39:41.583Z
links:
  docs: ./SKILL.md
source:
  repo: https://github.com/anthropics/skills
  path: skills/slack-gif-creator
  ref: main
  commit: 69c0b1a0674149f27b61b2635f935524b6add202
